In [1]:
import numpy as np

print("Matrix Unary Computations - Specific Problems")
print("=" * 50)

# Q3: What is the trace of the following matrix?
print("Q3: Trace of the given matrix")
print("-" * 30)

# Matrix B from the image
matrix_B = np.array([[10, 20, 30],
                     [5,  15, 25], 
                     [2,  4,  6]])

print("Matrix B:")
print(matrix_B)

# Calculate trace (sum of diagonal elements)
trace_B = np.trace(matrix_B)
print(f"\nTrace = {matrix_B[0,0]} + {matrix_B[1,1]} + {matrix_B[2,2]}")
print(f"Trace = {matrix_B[0,0]} + {matrix_B[1,1]} + {matrix_B[2,2]} = {trace_B}")

# Verify with manual calculation
manual_trace = matrix_B[0,0] + matrix_B[1,1] + matrix_B[2,2]
print(f"Manual verification: {manual_trace}")

print("\n" + "=" * 50)

# Practice Problem 2: Find the trace of a 5×5 identity matrix
print("Practice Problem 2: Trace of 5×5 Identity Matrix")
print("-" * 30)

# Create 5x5 identity matrix
identity_5x5 = np.eye(5)
print("5×5 Identity Matrix:")
print(identity_5x5)

# Calculate trace
trace_identity = np.trace(identity_5x5)
print(f"\nTrace of 5×5 Identity Matrix: {trace_identity}")
print("Note: The trace of an n×n identity matrix is always n")

print("\n" + "=" * 50)

# Practice Problem 3: Compute determinant of 3×3 matrix
print("Practice Problem 3: Determinant of 3×3 Matrix")
print("-" * 30)

# Matrix D from the image
matrix_D = np.array([[1, 2, 3],
                     [0, 4, 5],
                     [1, 0, 6]])

print("Matrix D:")
print(matrix_D)

# Calculate determinant using NumPy
det_D = np.linalg.det(matrix_D)
print(f"\nDeterminant using NumPy: {det_D}")

# Manual calculation using cofactor expansion (first row)
print("\nManual calculation using cofactor expansion along first row:")
print("det(D) = 1×(4×6 - 5×0) - 2×(0×6 - 5×1) + 3×(0×0 - 4×1)")
print(f"det(D) = 1×({4*6} - {5*0}) - 2×({0*6} - {5*1}) + 3×({0*0} - {4*1})")
print(f"det(D) = 1×{4*6 - 5*0} - 2×{0*6 - 5*1} + 3×{0*0 - 4*1}")
print(f"det(D) = {1*(4*6 - 5*0)} - {2*(0*6 - 5*1)} + {3*(0*0 - 4*1)}")
print(f"det(D) = {1*24} + {2*5} + {3*(-4)} = {24 + 10 - 12} = {22}")

manual_det_D = 1*(4*6 - 5*0) - 2*(0*6 - 5*1) + 3*(0*0 - 4*1)
print(f"\nVerification: Manual calculation = {manual_det_D}")

print("\n" + "=" * 50)

# Practice Problem 4: Application in Computer Science
print("Practice Problem 4: Computer Graphics Application")
print("-" * 30)

# Generate a random 3×3 matrix representing pixel intensities
np.random.seed(42)  # For reproducible results
pixel_matrix = np.random.randint(0, 256, (3, 3))  # Pixel values 0-255

print("3×3 Matrix representing pixel intensities:")
print(pixel_matrix)

# Find transpose
pixel_transpose = pixel_matrix.T
print("\nTranspose (useful for image transformations):")
print(pixel_transpose)

# Find determinant
pixel_determinant = np.linalg.det(pixel_matrix)
print(f"\nDeterminant: {pixel_determinant:.2f}")

print("\nApplication Note:")
print("- Transpose is used in image rotations and reflections")
print("- Determinant helps determine if transformations preserve area/orientation")

print("\n" + "=" * 50)

# Practice Problem 5: Symmetric Matrices in Machine Learning
print("Practice Problem 5: Symmetric Matrices in Machine Learning")
print("-" * 30)

# Create a symmetric 3×3 matrix (like a covariance matrix)
# Method: Create a matrix and make it symmetric
base_matrix = np.array([[4, 2, 1],
                        [3, 5, 2],
                        [1, 3, 6]])

# Make it symmetric by: (A + A.T) / 2
symmetric_ml = (base_matrix + base_matrix.T) / 2

print("Symmetric 3×3 Matrix (like a covariance matrix):")
print(symmetric_ml)

# Verify symmetric properties
print("\nVerifying symmetric properties:")
print("1. Is matrix equal to its transpose?", np.allclose(symmetric_ml, symmetric_ml.T))
print("2. Matrix shape:", symmetric_ml.shape)

# Additional properties important in ML
eigenvalues = np.linalg.eigvals(symmetric_ml)
print("3. Eigenvalues (all should be real):", eigenvalues)
print("4. Are all eigenvalues real?", np.all(np.isreal(eigenvalues)))
print("5. Trace:", np.trace(symmetric_ml))
print("6. Determinant:", np.linalg.det(symmetric_ml))

print("\nMachine Learning Note:")
print("- Symmetric matrices appear as covariance matrices in statistics")
print("- They have real eigenvalues and orthogonal eigenvectors")
print("- Used in PCA, quadratic forms, and optimization problems")

print("\n" + "=" * 50)
print("All specific problems completed! ✅")

Matrix Unary Computations - Specific Problems
Q3: Trace of the given matrix
------------------------------
Matrix B:
[[10 20 30]
 [ 5 15 25]
 [ 2  4  6]]

Trace = 10 + 15 + 6
Trace = 10 + 15 + 6 = 31
Manual verification: 31

Practice Problem 2: Trace of 5×5 Identity Matrix
------------------------------
5×5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Trace of 5×5 Identity Matrix: 5.0
Note: The trace of an n×n identity matrix is always n

Practice Problem 3: Determinant of 3×3 Matrix
------------------------------
Matrix D:
[[1 2 3]
 [0 4 5]
 [1 0 6]]

Determinant using NumPy: 22.000000000000004

Manual calculation using cofactor expansion along first row:
det(D) = 1×(4×6 - 5×0) - 2×(0×6 - 5×1) + 3×(0×0 - 4×1)
det(D) = 1×(24 - 0) - 2×(0 - 5) + 3×(0 - 4)
det(D) = 1×24 - 2×-5 + 3×-4
det(D) = 24 - -10 + -12
det(D) = 24 + 10 + -12 = 22 = 22

Verification: Manual calculation = 22

Practice Problem 4: Computer Graphics Applicati