In [1]:
# Student Activity: Introduction to NumPy for Matrix Applications
# Engr. Jamie Eduardo Rosal, MSCpE

import numpy as np
print("NumPy version:", np.__version__)
print("=" * 50)

# 1. Import NumPy and Create Matrices
print("1. CREATING MATRICES")
print("-" * 30)

# Create matrices A and B as specified
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("=" * 50)

# 2. Matrix Addition and Subtraction
print("2. MATRIX ADDITION AND SUBTRACTION")
print("-" * 30)

# Perform matrix addition and subtraction
C = A + B  # Addition
D = A - B  # Subtraction

print("Matrix Addition (A + B):")
print(C)
print("\nMatrix Subtraction (A - B):")
print(D)
print("=" * 50)

# 3. Matrix Multiplication
print("3. MATRIX MULTIPLICATION")
print("-" * 30)

# Element-wise multiplication (Hadamard product)
E = A * B
print("Element-wise Multiplication (A * B):")
print(E)

# Dot product multiplication (Matrix multiplication)
F = np.dot(A, B)
print("\nDot Product Multiplication (A · B):")
print(F)

# Alternative syntax for dot product
F_alt = A @ B
print("\nDot Product using @ operator (A @ B):")
print(F_alt)
print("=" * 50)

# 4. Determinant and Inverse of a Matrix
print("4. DETERMINANT AND INVERSE")
print("-" * 30)

# Calculate determinant of matrix A
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

# Calculate inverse of matrix A (if it exists)
try:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inv_A)
    
    # Verify the inverse by multiplying A with its inverse
    print("\nVerification (A × A⁻¹ should equal Identity matrix):")
    identity_check = np.dot(A, inv_A)
    print(np.round(identity_check, 10))  # Round to avoid floating point precision issues
    
except np.linalg.LinAlgError:
    print("Matrix A is singular (non-invertible)")

print("=" * 50)

# 5. Solving a System of Linear Equations
print("5. SOLVING SYSTEM OF LINEAR EQUATIONS")
print("-" * 30)

# System of equations:
# 2x + 3y = 8
# 5x + 7y = 19

print("Solving the system:")
print("2x + 3y = 8")
print("5x + 7y = 19")
print()

# Coefficient matrix and constant vector
coeff_matrix = np.array([[2, 3], [5, 7]])
const_matrix = np.array([8, 19])

print("Coefficient matrix:")
print(coeff_matrix)
print("\nConstant vector:")
print(const_matrix)

# Solve the system
solution = np.linalg.solve(coeff_matrix, const_matrix)
print(f"\nSolution: x = {solution[0]}, y = {solution[1]}")

# Verify the solution
print("\nVerification:")
print(f"2({solution[0]}) + 3({solution[1]}) = {2*solution[0] + 3*solution[1]}")
print(f"5({solution[0]}) + 7({solution[1]}) = {5*solution[0] + 7*solution[1]}")

print("=" * 50)

# Additional demonstrations and explanations
print("ADDITIONAL DEMONSTRATIONS")
print("-" * 30)

# Demonstrate matrix properties
print("Matrix A shape:", A.shape)
print("Matrix A data type:", A.dtype)
print("Matrix A transpose:")
print(A.T)

# Create larger matrices for more complex operations
print("\nLarger matrix example:")
large_A = np.random.randint(1, 10, size=(3, 3))
large_B = np.random.randint(1, 10, size=(3, 3))

print("Random 3x3 Matrix A:")
print(large_A)
print("Random 3x3 Matrix B:")
print(large_B)

print("\nDot product of 3x3 matrices:")
large_product = np.dot(large_A, large_B)
print(large_product)

# Eigenvalues and eigenvectors
print("\nEigenvalues and eigenvectors of original matrix A:")
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

print("=" * 50)

# Discussion Questions Answers
print("DISCUSSION QUESTIONS - ANSWERS")
print("-" * 30)

print("""
1. What is the difference between element-wise multiplication and dot product multiplication?

Answer: 
- Element-wise multiplication (A * B): Multiplies corresponding elements of matrices.
  Result: [[1*5, 2*6], [3*7, 4*8]] = [[5, 12], [21, 32]]
  
- Dot product multiplication (A @ B or np.dot(A,B)): Standard matrix multiplication.
  Result: [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]] = [[19, 22], [43, 50]]

2. What happens when a matrix is singular (i.e., non-invertible)?

Answer: 
- A singular matrix has a determinant of 0
- It cannot be inverted (no inverse exists)
- NumPy will raise a LinAlgError when trying to compute the inverse
- Systems of equations with singular coefficient matrices either have no solution or infinite solutions

3. Why is NumPy useful for numerical computing and matrix operations?

Answer:
- Optimized C/Fortran implementations make operations very fast
- Vectorized operations eliminate the need for explicit loops
- Rich linear algebra functionality (determinants, eigenvalues, etc.)
- Memory efficient storage and operations
- Integrates well with other scientific Python libraries
- Supports broadcasting for operations on arrays of different shapes
""")

NumPy version: 2.0.1
1. CREATING MATRICES
------------------------------
Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]
2. MATRIX ADDITION AND SUBTRACTION
------------------------------
Matrix Addition (A + B):
[[ 6  8]
 [10 12]]

Matrix Subtraction (A - B):
[[-4 -4]
 [-4 -4]]
3. MATRIX MULTIPLICATION
------------------------------
Element-wise Multiplication (A * B):
[[ 5 12]
 [21 32]]

Dot Product Multiplication (A · B):
[[19 22]
 [43 50]]

Dot Product using @ operator (A @ B):
[[19 22]
 [43 50]]
4. DETERMINANT AND INVERSE
------------------------------
Determinant of A: -2.0000000000000004
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A × A⁻¹ should equal Identity matrix):
[[1. 0.]
 [0. 1.]]
5. SOLVING SYSTEM OF LINEAR EQUATIONS
------------------------------
Solving the system:
2x + 3y = 8
5x + 7y = 19

Coefficient matrix:
[[2 3]
 [5 7]]

Constant vector:
[ 8 19]

Solution: x = 1.0, y = 2.0

Verification:
2(1.0) + 3(2.0) = 8.0
5(1.0) + 7(2.0) = 19.0
ADDITIONAL DEMONST